### ISSUE TITLE
How do _parseHandshake, _write, _onmessage and _onmessagelength work?

### ISSUE THREAD

**Issue by Fuck-You-GFW** [feross/bittorrent-protocol#13]
Hi! [L627-L689](https://github.com/feross/bittorrent-protocol/blob/master/index.js#L627-L689) and [L560-L576](https://github.com/feross/bittorrent-protocol/blob/master/index.js#L560-L576) is the most difficult to understand. I don't know how they work. Could you explain it?

Thanks!

**Comment by feross** [comment]
[L627-L689](https://github.com/feross/bittorrent-protocol/blob/master/index.js#L627-L689):

In short, the `_parse()` function takes a number of bytes that the local peer is waiting to receive from the remote peer, and a callback function to be called once that many bytes have arrived. So, `_parseHandshake()` just waits to receive a valid handshake. Whenever a complete message is received, then `this._parse(4, this._onmessagelength)` is called, which basically just waits for the next message. It's waiting for 4 bytes since that'll give the length of the message to follow. Then, once that many bytes have come, the appropriate method is called for whatever type of message it might be.

You can read [BEP3](http://www.bittorrent.org/beps/bep_0003.html) to learn about the different message types in the bittorrent protocol.

[L560-L576](https://github.com/feross/bittorrent-protocol/blob/master/index.js#L560-L576):

`_write()` is a method that all Node.js writable streams must implement. You can see the docs for Node.js streams [here](https://nodejs.org/api/stream.html). I also highly recommend the [Streams Handbook](https://github.com/substack/stream-handbook) for learning all about streams. So anyway, `_write()` gets called by the streams implementation whenever the remote peer sends data. Data that the remote peer sends us gets buffered (i.e. not actually processed) until the right number of bytes have arrived, determined by the call to `this._parse(number, callback)` as mentioned before. Once enough bytes have arrived to process the message, the callback function passed to `this._parse()` gets called with the full buffer of data.

**Comment by feross** [comment]
I just updated the codebase to include comments about how this all works.

**Comment by Fuck-You-GFW** [comment]
I understood how they work now, although I am still incomprehensible in the code. But It is no matter, I copy the some code to my project. :)

Thank you very much!
